spring:
  application:
    name: mychat-back
  profiles:
    active: local

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.khj.mychatback: debug
